hook.Add("PopulateToolMenu", "paranatural", function()
    local allow_telekinesis, allow_shield, allow_levitation, allow_dash
    spawnmenu.AddToolMenuOption("Utilities", "Paranatural", "paranatural_a_settings", "Server Settings", "", "", function(panel)
        panel:Clear()
        panel:Help("This tab will NOT do anything if you don't have admin permissions on the server.")
        allow_telekinesis = panel:CheckBox("Allow Telekinesis usage to everyone", "")
        panel:ControlHelp("If unchecked, will limit usage to only admins.")
        allow_shield = panel:CheckBox("Allow Shield usage to everyone", "")
        panel:ControlHelp("If unchecked, will limit usage to only admins.")
        allow_dash = panel:CheckBox("Allow Dash usage to everyone", "")
        panel:ControlHelp("If unchecked, will limit usage to only admins.")
        allow_levitation = panel:CheckBox("Allow Levitation usage to everyone", "")
        panel:ControlHelp("If unchecked, will limit usage to only admins.")

        function allow_telekinesis:OnChange(val)
            net.Start("paranatural")
                net.WriteUInt(1, 1)
                net.WriteString("paranatural_telekinesis_allowed")
                net.WriteString(val and "1" or "0")
            net.SendToServer()
        end
        allow_telekinesis:SetConVar(nil)
        function allow_shield:OnChange(val) 
            net.Start("paranatural")
                net.WriteUInt(1, 1)
                net.WriteString("paranatural_shield_allowed")
                net.WriteString(val and "1" or "0")
            net.SendToServer() end
        allow_shield:SetConVar(nil)
        function allow_dash:OnChange(val) 
            net.Start("paranatural")
                net.WriteUInt(1, 1)
                net.WriteString("paranatural_dash_allowed")
                net.WriteString(val and "1" or "0")
            net.SendToServer() end
        allow_dash:SetConVar(nil)
        function allow_levitation:OnChange(val) 
            net.Start("paranatural")
                net.WriteUInt(1, 1)
                net.WriteString("paranatural_levitation_allowed")
                net.WriteString(val and "1" or "0")
            net.SendToServer() end
        allow_levitation:SetConVar(nil)

        net.Start("paranatural") net.WriteUInt(0, 1) net.WriteString("paranatural_telekinesis_allowed") net.SendToServer()
        net.Start("paranatural") net.WriteUInt(0, 1) net.WriteString("paranatural_shield_allowed") net.SendToServer()
        net.Start("paranatural") net.WriteUInt(0, 1) net.WriteString("paranatural_dash_allowed") net.SendToServer()
        net.Start("paranatural") net.WriteUInt(0, 1) net.WriteString("paranatural_levitation_allowed") net.SendToServer()

        net.Receive("paranatural", function(_, ply)
            local cv, val = net.ReadString(), net.ReadString() == "1"
            if cv == "paranatural_telekinesis_allowed" then allow_telekinesis:SetValue(val) end
            if cv == "paranatural_shield_allowed" then allow_shield:SetValue(val) end
            if cv == "paranatural_dash_allowed" then allow_dash:SetValue(val) end
            if cv == "paranatural_levitation_allowed" then allow_levitation:SetValue(val) end
        end)
    end)
    spawnmenu.AddToolMenuOption("Utilities", "Paranatural", "paranatural_settings", "Settings", "", "", function(panel)
        panel:Clear()
        panel:Help("Abilities toggles")
        panel:ControlHelp("Please note that toggling these while using ability will make you unable to stop using disabled ability until you turn it back off and stop using it. For example, you won't be able to let go of a prop you hold with telekinesis ability if you disabled it.")
        panel:CheckBox("Enable Telekinesis", "paranatural_telekinesis_enable")
        panel:ControlHelp("Telekinesis is an ability to grab and throw various entities.")
        panel:CheckBox("Enable Shield", "paranatural_shield_enable")
        panel:ControlHelp("Shield lets you protect yourself with props that you rip out of the ground.")
        panel:CheckBox("Enable Dash", "paranatural_dash_enable")
        panel:ControlHelp("Dash is ability that sends you in the direction you are looking with a great force, damaging everything in your way")
        panel:CheckBox("Enable Levitation", "paranatural_levitation_enable")
        panel:ControlHelp("Levitation lets you levitate above the ground and break your falling avoiding the damage.")
    end)
    spawnmenu.AddToolMenuOption("Utilities", "Paranatural", "paranatural_binds", "Bindings", "", "", function(panel)
        panel:Clear()
        panel:KeyBinder("Telekinesis", "paranatural_telekinesis_key")
        panel:KeyBinder("Shield", "paranatural_shield_key")
        panel:KeyBinder("Dash", "paranatural_dash_key")
    end)

    spawnmenu.AddToolMenuOption("Utilities", "Paranatural", "paranatural_sw_forms", "Service Weapon: Forms", "", "", function(panel)
        panel:Clear()
        panel:Help("Form #1")
        panel:Button("Grip", "paranatural_weapon_form_1", "grip")
        panel:ControlHelp("A standard sidearm form similar to a revolver. It has high accuracy and single-shot damage.")
        panel:Button("Spin", "paranatural_weapon_form_1", "spin")
        panel:ControlHelp("A rapid-fire form with lower accuracy and single shot damage, but a significantly higher rate of fire. Good for medium-range combat.")
        panel:Button("Shatter", "paranatural_weapon_form_1", "shatter")
        panel:ControlHelp("A form similar to a shotgun with a wide blast radius, but shorter effective range.")
        panel:Button("Pierce", "paranatural_weapon_form_1", "pierce")
        panel:ControlHelp("A form that charges a powerful, single shot that can one-shot or significantly damage many enemies.")
        panel:Button("Charge", "paranatural_weapon_form_1", "charge")
        panel:ControlHelp("A form that shoots explosives. Can damage owner as well, take care.")
        panel:Help("Form #2")
        panel:Button("Grip", "paranatural_weapon_form_2", "grip")
        panel:ControlHelp("A standard sidearm form similar to a revolver. It has high accuracy and single-shot damage.")
        panel:Button("Spin", "paranatural_weapon_form_2", "spin")
        panel:ControlHelp("A rapid-fire form with lower accuracy and single shot damage, but a significantly higher rate of fire. Good for medium-range combat.")
        panel:Button("Shatter", "paranatural_weapon_form_2", "shatter")
        panel:ControlHelp("A form similar to a shotgun with a wide blast radius, but shorter effective range.")
        panel:Button("Pierce", "paranatural_weapon_form_2", "pierce")
        panel:ControlHelp("A form that charges a powerful, single shot that can one-shot or significantly damage many enemies.")
        panel:Button("Charge", "paranatural_weapon_form_2", "charge")
        panel:ControlHelp("A form that shoots explosives. Can damage owner as well, take care.")
    end)
end)

local telekinesis_enable = CreateClientConVar("paranatural_telekinesis_enable", "1", true, true)
local shield_enable = CreateClientConVar("paranatural_shield_enable", "1", true, true)
local dash_enable = CreateClientConVar("paranatural_dash_enable", "1", true, true)
local levitation_enable = CreateClientConVar("paranatural_levitation_enable", "1", true, true)
local form_1 = CreateClientConVar("paranatural_weapon_form_1", "grip", true, true)
local form_2 = CreateClientConVar("paranatural_weapon_form_2", "spin", true, true)